version: '3.8'

services:
  app: &app
    build:
      context: .
      dockerfile: dockerfile
    command: php artisan octane:start --watch --host=0.0.0.0 --workers=4
    volumes:
      - "./:/app"
    ports:
      - 8000:8000